#!ruby
require_relative "../lib/mocmock.rb"

dir = ARGV[0]

if dir.nil?
  puts "ERROR:"
  puts "  Give Project name"
  puts
  puts "USAGE:"
  puts "  mocmock new [PROJECT_NAME]"
  return
end

MocMock.init dir
